'use strict';
// Catalyst Function: nightly NETRA "Beat Briefing".
// Triggered by a Catalyst Cron (see ../../cron-beat-briefing.json, schedule 0 6 * * *).
// Builds a per-district intelligence briefing (emerging hotspots, active near-repeat series,
// watch-list offenders) and DISPATCHES it via Catalyst Mail (and optionally Push), turning the
// on-demand /briefing page into a proactive, scheduled alert (PS1 §8).
//
// This is real, deploy-ready code: on Catalyst it imports NETRA's briefing engine over the same
// canonical schema. Reads come from the seed by default; point at Catalyst Data Store in prod.

const catalyst = require('zcatalyst-sdk-node');

const DISTRICTS = ['Bengaluru Urban', 'Mysuru', 'Hubballi', 'Kalaburagi', 'Belagavi'];

module.exports = async (cronDetails, context) => {
  try {
    const { generateBriefing } = await import('@netra/core/briefing');
    const { loadDataset } = await import('@netra/core/dataset');
    const app = catalyst.initialize(context);
    const ds = loadDataset(); // prod: replace with Catalyst Data Store reads

    for (const district of DISTRICTS) {
      const b = generateBriefing(ds, { district });
      const subject = `NETRA Beat Briefing — ${district} — ${b.summary.active_series} active series, ${b.summary.emerging_hotspots} emerging hotspots`;
      const content = renderBriefing(district, b);

      // Catalyst Mail (verified sender required: set NETRA_MAIL_FROM / NETRA_MAIL_TO)
      if (process.env.NETRA_MAIL_FROM) {
        try {
          await app.email().sendMail({
            from_email: process.env.NETRA_MAIL_FROM,
            to_email: [process.env.NETRA_MAIL_TO || process.env.NETRA_MAIL_FROM],
            subject,
            content,
          });
        } catch (e) { console.error(`[beatBriefing] mail failed for ${district}:`, e.message); }
      }
      // Optional: Catalyst Push Notifications to station officers' devices
      // await app.push().sendNotification(...);
      console.log(`[beatBriefing] ${district}: ${b.summary.active_series} series, ${b.summary.emerging_hotspots} hotspots, ${b.summary.watch_offenders} watch`);
    }
    if (context && context.closeWithSuccess) context.closeWithSuccess();
  } catch (e) {
    console.error('[beatBriefing] failed:', e);
    if (context && context.closeWithFailure) context.closeWithFailure();
  }
};

function renderBriefing(district, b) {
  const lines = [`NETRA Beat Briefing — ${district}`, `Generated ${b.generated_at}`, ''];
  lines.push(`Active near-repeat series (deploy tonight):`);
  if (!b.active_series.length) lines.push('  none');
  for (const s of b.active_series) {
    lines.push(`  • ${s.crime} near ${s.station} — ${s.cluster.observed} in 1.5km/40d (p=${s.cluster.p})` +
      (s.forecast ? `, next window ${s.forecast.eta.start.slice(0, 10)}→${s.forecast.eta.end.slice(0, 10)}` : ''));
  }
  lines.push('', 'Emerging hotspots (14–30d):');
  for (const e of b.emerging) lines.push(`  • ${e.crime} @ ${e.station} (z=${e.z}, n=${e.count})`);
  lines.push('', 'Offenders to watch:');
  for (const o of b.watch_offenders) lines.push(`  • ${o.name} — risk ${o.score}/100 (${o.band})`);
  lines.push('', '— Generated by NETRA. Findings carry evidence trails. (Prototype: labelled synthetic data.)');
  return lines.join('\n');
}
