// Converts NETRA's seed dataset (data/seed/*.json) into Catalyst-Data-Store-ready CSVs.
// The Data Store console bulk-imports CSV with column mapping, so this is the fastest,
// zero-credential path to get all 9 tables live once the Catalyst project exists.
//
//   node catalyst/scripts/seed-to-csv.mjs        → writes data/csv/*.csv + _SCHEMA.md
//
// Conventions (documented in data/csv/_SCHEMA.md for the console import):
//  - arrays (mo_tags, ipc_bns_sections, source_fir_ids, mo_fingerprint) → pipe-joined text
//  - booleans → true/false text; datetimes stay ISO-8601 strings
//  - every value CSV-escaped (quotes doubled, fields with commas/quotes/newlines quoted)

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SEED = join(__dirname, '..', '..', 'data', 'seed');
const OUT = join(__dirname, '..', '..', 'data', 'csv');

const TABLES = [
  'districts', 'stations', 'persons', 'firs',
  'fir_accused', 'fir_victim', 'associations', 'accounts', 'transactions',
];

const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/;
const esc = (v) => {
  if (v === null || v === undefined) return '';
  let s;
  if (Array.isArray(v)) s = v.join('|');
  else if (typeof v === 'string' && ISO.test(v)) s = v.slice(0, 19).replace('T', ' '); // Catalyst DateTime: YYYY-MM-DD HH:MM:SS
  else if (typeof v === 'object') s = JSON.stringify(v);
  else s = String(v);
  if (/[",\n\r]/.test(s)) s = '"' + s.replace(/"/g, '""') + '"';
  return s;
};

mkdirSync(OUT, { recursive: true });
const schemaLines = ['# Catalyst Data Store import schema', '', 'Generated by `node catalyst/scripts/seed-to-csv.mjs`. Import each CSV into a Data Store table of the same name (console → Data Store → Import). Arrays are pipe-joined text; datetimes are ISO-8601 text; booleans are true/false.', ''];

let total = 0;
for (const name of TABLES) {
  const file = join(SEED, `${name}.json`);
  if (!existsSync(file)) { console.warn(`skip ${name} (missing)`); continue; }
  const rows = JSON.parse(readFileSync(file, 'utf8'));
  if (!rows.length) { console.warn(`skip ${name} (empty)`); continue; }
  // union of keys across rows, preserving first-seen order
  const cols = [];
  for (const r of rows) for (const k of Object.keys(r)) if (!cols.includes(k)) cols.push(k);
  const lines = [cols.join(',')];
  for (const r of rows) lines.push(cols.map((c) => esc(r[c])).join(','));
  writeFileSync(join(OUT, `${name}.csv`), lines.join('\n'));
  total += rows.length;

  schemaLines.push(`## ${name} (${rows.length} rows)`);
  const sample = rows[0];
  for (const c of cols) {
    const v = sample[c];
    const type = Array.isArray(v) ? 'text (pipe-joined array)'
      : typeof v === 'number' ? (Number.isInteger(v) ? 'int' : 'double')
      : typeof v === 'boolean' ? 'boolean'
      : /^\d{4}-\d{2}-\d{2}T/.test(String(v)) ? 'datetime (ISO text)'
      : 'text';
    schemaLines.push(`- \`${c}\` — ${type}`);
  }
  schemaLines.push('');
}
writeFileSync(join(OUT, '_SCHEMA.md'), schemaLines.join('\n'));
console.log(`Wrote ${TABLES.length} CSVs (${total} rows) + _SCHEMA.md → ${OUT}`);
